### ISSUE TITLE
TN

### ISSUE THREAD

**Issue by jeduan** [pollero/pollero#1]
La visa TN es la forma más fácil de trabajar legalmente en Estados Unidos

**Comment by fedesoria** [comment]
https://www.youtube.com/watch?v=hHGY9dxYl-U

**Comment by nithinusrecruiter** [comment]
Yes, Working on Tn Visa legally in USA is really a very good opportunity for the Mexico citizens. For more information you can send me a email to nithin.usrecruiter@gmail.com

**Comment by teranpri** [comment]
Hola todos! soy nueva en esto de la TN, me podrían dar sus recomendaciones please?

gracias!

**Comment by solojavier** [comment]
El README contiene la información general sobre la visa: https://github.com/tnstatus/tnstatus/blob/master/README.md

¿Tienes alguna duda o situación en particular?
