### ISSUE TITLE
TN Etampada por 1 año, I-94 por 3 años. 

### ISSUE THREAD

**Issue by jorgef21** [pollero/pollero#30]
Hola  a todos,

Encuentro este sitio muy interesante y desearia haber leido algunas cosas antes de empezar solo este proceso de mi visa TN.

Actualmente me encuentro trabajando en U.S bajo esta visa por casi un año, mi visa en el consulado me la estamparon por solo ese tiempo pero al momento de cruzar la frontere me dieron mi permiso I-94 por 3 años lo que mostraba en mi carta.

Entiendo que puedo permanecer 3 años legalmente trabajando en usa aun mi visa este vencida ya que mi permiso es por 3 años. 

Mis preguntas son:

Ua ves mi visa se venza tengo entendido no puedo viajar fuera de estados unidos y regresar? aun mi permiso siga vigente.

Para renovacion de la visa, tengo que pasar por todo el proceso? Huellas cita al CAS, Entrevista en el consulado, etc...

En este link dice claramente que la vis TN puede calificar para extension sin entrevista siempre y cuando no rebase los 12 meses de expiracio:
https://mx.usembassy.gov/es/visas-es/renovaciones/

Pero no estoy muy seguro de esta informacion ya que nadie me lo ha podido confirmar y al momento de hacer tu cita siempre te da opcion de seleccionar 2.

Otra pregunta mas:

En caso de renovar mi visa TN, al momento de cruzar la frontera tengo que obtener un nuevo permiso I-94, el mio sigue vigente hasta 2021.

Gracias por su ayuda, posteriormente les contare mi experiencia con esta visa.

**Comment by MexicanHacker** [comment]
Jorge,

1. Una vez vencida tu visa no podrías entrar de vuelta a USA si sales a menos que la renueves. Es correcto como lo vez, la I-94 rige y determina tu estancia en USA.
2. El proceso de si es una o dos entrevistas lo determina el CAS, siempre se hacen dos entrevistas y cuando vas al CAS ellos deciden si tienes todo en orden para ya no ir al consulado, normalmente es cuando es renovación anual con el mismo empleo
3. Si sales y vuelves a entrar se genera otro I-94 que puede ser por un año o 3 años dependiendo del consul en la entrada.

**Comment by alexise26** [comment]
Hola Jorge,
Espero que te encuentres muy bien. Yo actualmente trabajo con visa TN en una ciudad fronteriza (México-USA), cuando la obtuve, la vigencia de mi visa era de 1 año, y la de mi I-94 por 3. Espero que mis respuestas te sean de ayuda.

**> Ua ves mi visa se venza tengo entendido no puedo viajar fuera de estados unidos y regresar? aun mi permiso siga vigente.**
En este momento tengo mi visa vencida, pero mi I-94 sigue vigente, y no he tenido problemas para salir o entrar del país, ojo, **por tierra**, por que si sales por aire o por mar te retiran tu I-94 y al volver debes solicitar uno nuevo, y con tu visa expirada esto no sería posible. En cambio por tierra, no te retiran tu I-94.

**> Para renovacion de la visa, tengo que pasar por todo el proceso? Huellas cita al CAS, Entrevista en el consulado, etc...**
En cuanto a la renovación, personalmente a mí no me ha tocado renovar, apenas tengo un año trabajando en USA, pero he escuchado de compañeros que llevan todo el proceso normal y de otros a los que les retiran la visa en el CAS y les dicen que no es necesario ir al Consulado, por lo tanto en el mismo CAS les procesan la renovación de su visa. No estoy muy seguro del criterio, pero el compañero que renovó en el CAS sin ir al Consulado tenía menos de un año de que se expirara su visa, mientras otros esperan hasta que se expire el I-94 para renovar, así que puede ser por ahí.

**> En caso de renovar mi visa TN, al momento de cruzar la frontera tengo que obtener un nuevo permiso I-94, el mio sigue vigente hasta 2021.**
Por último, eso del I-94 depende mucho del oficial fronterizo que lo entregue. Por lo que yo sé, cuando vas a renovar se quedan con tu Visa e I-94, así que el hecho de que tengas tu I-94 por más tiempo restante, no es garantía de que lo vayan a respetar. Uno de mis compañeros renovó su visa al expirar y le restaban 2 años en su I-94, y al sacar su nuevo I-94, nomás se lo dieron por 1 año. Es cuestión de criterios.

Saludos Jorge,

Alexis

**Comment by jorgef21** [comment]
> * El proceso de si es una o dos entrevistas lo determina el CAS, siempre se hacen dos entrevistas y cuando vas al CAS ellos deciden si tienes todo en orden para ya no ir al consulado, normalmente es cuando es renovación anual con el mismo empleo

Gracias por compartir sus experiencias, en verdad creo que hay vastante desinformacion respecto a la visa TN y todo entorno a ella incluso con los oficiales en la frontera.

Actualmente si pienso renovar con el mismo empleador por lo cual creo calificaria para renovar sin entrevista pero ya dependeria del CAS.

En cuanto al caso de que puedes seguir viajando aunque tu visa este vencida pero no tu I-94 creo que esta un poco confuso ya que hay documentos del USCIS que asi lo senalan incluso la experiencia de @alexise26

**Comment by jorgef21** [comment]
@alexise26  Gracias por tu respuesta, en verdad me ayuda mucho para decidir que hacer con mi situacion actual, una consulta por que frontera estas entrando Tijuana-CA? Las 2 veces que e ingresado con visa tn es por CA.

Estoy indeciso si renovar visa o no por el gasto y posibles riesgos de que la I-94 la den por menor tiempo ya que actualmente es por 3 anios(Aun me quedan 2 hasta 2021).

Uno de los problemas que tambien tengo es que mi esposa cuenta con visa TD, en cambio a ella le dieron su I-94 con la misma expiracion de la visa (Mayo 2019, mi visa tamben vence MAyo 2019 pero I-94 2021) leyendo un poco de informacion creo que fue por la expiracion de su pasaporte en este mismo anio, en cambio el mio tiene validez por 4 anios mas.

Ahora unas preguntas extra si es que tienen experienca con visa de sus dependientes:

Puede salir ella digamos a la frontera de mexico/canada y reingresar antes de que su visa expire pero con un pasaporte renovado y renovar su I-94?

Posteriormente que nuestra visa expire (Mayo 2019) podremos viajar ambos con nuestra I-94 vigente y visa vencida? ya sea a mexico o canada 

Este tipo de cuestiones parece muy trivial ya que parece variar en cuanto a diferentes experiencias, en otros foros eh consultado y muchos indican que tu visa debe estar vijente al momento de cruzar, otros indican que solo tu I-94, incluso realice una llamada al USCIS quienes me indicaron que es a discrecion del oficial si te deja entrar o no lo que me parece bastante complicado decidir.

Gracias por sus respuestas, @alexise26  @MexicanHacker

**Comment by alexise26** [comment]
Hola nuevamente Jorge,

Yo vivo en El Paso, TX, así que cruzo seguido a Cd. Juárez, y lo hago por diferentes puntos de entrada. Como te comentaba, he cruzado con mi visa vencida, precisamente lo hice ayer, lo único que me piden es que mi I-94 este vigente. Hasta hoy he entrado con mi visa vencida por 3 puentes internacionales diferentes y no he tenido problema alguno, solo revisan que mi I-94 no este vencido, lo peor que me ha pasado es que me han hecho el comentario de que mi Visa esta vencida, que la renueve cuando tenga oportunidad, pero aún así me dejan entrar. Incluso tengo muchos compañeros que viven en Cd. Juárez y cruzan diariamente  a trabajar aquí con su visa vencida y el I-94 vigente.

En cuanto a la situación de tu esposa, se me hace un territorio un poco desconocido, pues nunca he estado en esa situación, pero si su visa vence en Mayo y la tuya también, creo que es muy probable que te forcen a renovar tu visa para poder renovar la de ella también. Dudo mucho que le den un nuevo I-94 con su visa vencida aunque tenga su nuevo pasaporte mexicano vigente, pues lo que usan para expedir el I-94 es la Visa.

Si vas a renovar pasaporte mexicano, te recomiendo que lo hagas en USA, yo lo hice en la Embajada Mexicana en El Paso y siento que fue más rapido y sencillo que hacerlo en México.

Saludos de nuevo, primo!

Alexis Escalante

**Comment by jorgef21** [comment]
Gracias por tu pronta respuesta, otra cosa que estaba pensando es como te comento  viajar a la frontera ya sea mexico o canada antes de que nuestras visas expiren que seria antes del 29 de Mayo 2019(salir y entrar por tierra) asi mi I-94 se conserva vigente y solo extenderiamos su I-94, crees que esto sea posible o exista algun riesgo de que a ella o incluso a los dos nos nieguen la entrada u obliguen a renovar nuestra TN-TD @alexise26

**Comment by jorgef21** [comment]
gracias a todos por sus respuestas, solo acudi a la frontera de Canada antes de que nuestras visas expiraran y a mi esposa le dieron I-94 igual que mi tiempo. Se nos vence 2021 ambos y nuestra visa ya vencione m mayo.

**Comment by teranpri** [comment]
alguien me podría dar información de cómo se consigue al I-94? es en CBP llegando al aeropuerto? y con la visa TN y pasaporte+ la carta de empleo es lo único necesario?
no tengo idea de este trámite, muchas gracias!!

**Comment by JavoTamez** [comment]
> Hola Jorge, Espero que te encuentres muy bien. Yo actualmente trabajo con visa TN en una ciudad fronteriza (México-USA), cuando la obtuve, la vigencia de mi visa era de 1 año, y la de mi I-94 por 3. Espero que mis respuestas te sean de ayuda.
> 
> **> Ua ves mi visa se venza tengo entendido no puedo viajar fuera de estados unidos y regresar? aun mi permiso siga vigente.** En este momento tengo mi visa vencida, pero mi I-94 sigue vigente, y no he tenido problemas para salir o entrar del país, ojo, **por tierra**, por que si sales por aire o por mar te retiran tu I-94 y al volver debes solicitar uno nuevo, y con tu visa expirada esto no sería posible. En cambio por tierra, no te retiran tu I-94.
> 
> **> Para renovacion de la visa, tengo que pasar por todo el proceso? Huellas cita al CAS, Entrevista en el consulado, etc...** En cuanto a la renovación, personalmente a mí no me ha tocado renovar, apenas tengo un año trabajando en USA, pero he escuchado de compañeros que llevan todo el proceso normal y de otros a los que les retiran la visa en el CAS y les dicen que no es necesario ir al Consulado, por lo tanto en el mismo CAS les procesan la renovación de su visa. No estoy muy seguro del criterio, pero el compañero que renovó en el CAS sin ir al Consulado tenía menos de un año de que se expirara su visa, mientras otros esperan hasta que se expire el I-94 para renovar, así que puede ser por ahí.
> 
> **> En caso de renovar mi visa TN, al momento de cruzar la frontera tengo que obtener un nuevo permiso I-94, el mio sigue vigente hasta 2021.** Por último, eso del I-94 depende mucho del oficial fronterizo que lo entregue. Por lo que yo sé, cuando vas a renovar se quedan con tu Visa e I-94, así que el hecho de que tengas tu I-94 por más tiempo restante, no es garantía de que lo vayan a respetar. Uno de mis compañeros renovó su visa al expirar y le restaban 2 años en su I-94, y al sacar su nuevo I-94, nomás se lo dieron por 1 año. Es cuestión de criterios.
> 
> Saludos Jorge,
> 
> Alexis

Hola Alexis......Yo tambien soy de Cd Juarez...trengo mi Visa TN expirada , pero el permiso I94 Vigenet hasta 2025....¿puedo viajar por Avion dentro de USA...saliendo del Paso a Chicago?
