### ISSUE TITLE
visas TN NAFTA con cedula profesional electrónica

### ISSUE THREAD

**Issue by jacoballeza** [pollero/pollero#34]
Que tal buena tarde
Alguien aquí sabe si puedo hacer mi trámite de visa TN NAFTA con la cedula profesional electrónica, ya que perdí la física y/o con el título en físico?

**Comment by jeduan** [comment]
duplicado de #33

**Comment by mauber91** [comment]
Igual tengo esa duda, sobre todo porque se supone que no te dejan entrar con dispositivos electrónicos, entonces, cómo muestras la cédula electrónica? O te piden el número de cédula solamente? La debería de imprimir en hoja "normal"?
