### ISSUE TITLE
Es posible trabajar con TN expirada y con I-94 vigente?

### ISSUE THREAD

**Issue by MrcRjs** [pollero/pollero#48]
Hola que tal! Alguien sabe si es posible seguir trabajando desde USA sin tener una visa vigente pero teniendo la I-94 todavia vigente? 

Muchas gracias!

**Comment by carlosdiaz** [comment]
Legalmente no creo que esto sea posible, son cosas completamente diferentes, la primera te permite laborar mientras que la segunda te permite transitar en el pais siempre y cuando la primera sea vigente hasta donde entiendo.

**Comment by jeduan** [comment]
Cuando dices que tu i94 está vigente entraste con TN? Mi entendimiento es que la visa stamp te permite entrar y el i94 es tu permiso de estar dentro y realizar actividades que tu status de entrada te permite.

**Comment by MrcRjs** [comment]
@carlosdiaz @jeduan gracias por sus respuestas. Así es, entré con TN pero esta por vencer y tengo la duda si tengo que salir, finalizar mi contrato y trabajar "contractor" desde México hasta que renueve o tenga otra Visa TN.
